# deployment using blue-green deployment


name: Green Deployment
on: 
    push: 
      branches: 
        - main

jobs: 
  testdeployment:
    if: ${{ github.ref_name == 'main' }}
    runs-on: ubuntu-latest
    steps: 
      - name: "first run job"
        run: |
          echo "--- welcome to bloggin app ----"
      
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Create version number"
        run: |
          echo "VERSION_NUMBER=${RANDOM}" >> $GITHUB_ENV
      
      - name: "Build a Docker image from the repo v1"
        run:  | 
          docker build -t healerkay/bloggin:${{ env.VERSION_NUMBER}} .

      - name: "Log into Docker Hub"
        uses: docker/login-action@v3
        with: 
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: "Push to Docker Hub"
        run: |
          docker push healerkay/bloggin:${{ env.VERSION_NUMBER }}

      - name: "Install kubectl"
        uses: azure/setup-kubectl@v3
        with: 
          version: "v1.19.3"
        id: "install-kubectl"

      - name: "Setup AWS Credentials"
        uses: aws-actions/configure-aws-credentials@v4
        with: 
          aws-region: "us-east-1"
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key:  ${{ secrets.AWS_SECRET_KEY }}

      - name: "Connect to the cluster"
        run: |
          aws eks update-kubeconfig --name <name>


      - name: "Install Helm"
        uses: azure/setup-helm@v4.2.0
        id: "install-helm"

      - name: "Use helm to install our charts"
        run: |
          helm upgrade --install bloggin bloggin -f bloggin/values.yaml --set image.tag=${{ env.VERSION_NUMBER}} --set replicaCount=4

